baseURL = "https://limoges.io"
languageCode = "en-ca"
title = "Julien Limoges"
theme = "alpenfrisch"
publishDir = "docs"
canonifyURLs = true
copyright = ""

pygmentsCodeFences = true
pygmentsUseClasses = true

[author]
  name = "Julien Limoges"

[social]
  github = "https://github.com/limoges"
  linkedin = "https://www.linkedin.com/in/julienlimoges/"
  facebook = "https://www.facebook.com/julienlimoges"
  twitter = "https://twitter.com/julienlimoges"

[taxonomies]
tags = "tags"

